### PR TITLE
JSB-1198 Completely rewritten the Lambda handlers to use play json

### PR DESCRIPTION
**Pull request by gvince01**
[JIRA](https://pharmpress.atlassian.net/browse/JSB-1198)

Rewrote the library to use the play json library instead of using circe

### CODE REVIEW

**Review by krishna-thapa — DISMISSED** [review]
Looks all good to me :+1:

**Review by MicheleMorelli — DISMISSED** [review]
It looks good to me!

@gvince01 just a quick curiosity: why have you decided to make this switch from Circe to Play's `Json`?
was it for consistency with what we use in the other apps?

**Comment by gvince01** [comment]
@MicheleMorelli After looking at our `.zip` package (text-service backend) I notice that cats appears to take up ~35% of the size of the zip. Cats is being pulled in by circe which is being used for json encoding/decoding. I’ve rewritten the app using play json which meant I could remove cats. The resulting zip is 24 Mb (vs 37Mb currently).

**Comment by MicheleMorelli** [comment]
@gvince01 Good call!

**Review by krishna-thapa — APPROVED** [review]
To release :+1:

**Pull request merged**
